Repository 3-isekaiSSG/isekai-be, pull requests merged in 2024-04, with the labels that each got.

#76 Feature/order-filter
  ssgserver/src/main/java/com/isekai/ssgserver/order/controller/OrderController.java
  ssgserver/src/main/java/com/isekai/ssgserver/order/dto/OrderListDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/order/repository/OrderCustomRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/order/service/OrderService.java
Labels: 📬 API, ✨ Feature

#79 Feature/address
  ssgserver/src/main/java/com/isekai/ssgserver/common/dto/DataIdDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/deliveryAddress/controller/DeliveryAddressController.java
  ssgserver/src/main/java/com/isekai/ssgserver/deliveryAddress/dto/DeliveryAddressCreateDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/deliveryAddress/dto/DeliveryAddressIdDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/deliveryAddress/dto/DeliveryAddressInfoDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/deliveryAddress/entity/DeliveryAddress.java
  ssgserver/src/main/java/com/isekai/ssgserver/deliveryAddress/repository/DeliveryAddressRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/deliveryAddress/service/DeliveryAddressService.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/service/MemberService.java
Labels: 📬 API, ✨ Feature

#81 Feat: 소셜로그인 매핑
  ssgserver/src/main/java/com/isekai/ssgserver/member/controller/MemberController.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/dto/MemberJoinDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/dto/SocialMappingDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/service/MemberService.java
Labels: 📬 API, ✨ Feature

#84 Feature/social
  ssgserver/src/main/java/com/isekai/ssgserver/member/controller/MemberController.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/dto/SocialJoinDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/dto/SocialMappingDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/service/MemberService.java
Labels: 📬 API, ✨ Feature

#83 Feature/cart
  ssgserver/src/main/java/com/isekai/ssgserver/cart/controller/CartController.java
  ssgserver/src/main/java/com/isekai/ssgserver/cart/entity/Cart.java
  ssgserver/src/main/java/com/isekai/ssgserver/cart/service/CartService.java
  ssgserver/src/main/java/com/isekai/ssgserver/cart/service/CartUpdateService.java
  ssgserver/src/main/java/com/isekai/ssgserver/config/CorsConfig.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/controller/MemberController.java
Labels: 📬 API, ✨ Feature

#86 Feat: 소셜 매핑 Dto 수정
  ssgserver/src/main/java/com/isekai/ssgserver/member/dto/SocialJoinDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/dto/SocialMappingDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/service/MemberService.java
Labels: 📬 API, 🐞 BugFix, ✨ Feature

#88 Feature/cart
  ssgserver/src/main/java/com/isekai/ssgserver/cart/controller/CartController.java
Labels: 📬 API, ✨ Feature

#89 Fix: 비회원 장바구니 value 저장
  ssgserver/src/main/java/com/isekai/ssgserver/cart/service/CartService.java
Labels: 📬 API, 🐞 BugFix, ✨ Feature

#90 Chore/setting
  ssgserver/src/main/java/com/isekai/ssgserver/config/CorsConfig.java
Labels: ⚙ Setting, 🐞 BugFix

#92 Feature/cart
  ssgserver/src/main/java/com/isekai/ssgserver/cart/service/CartService.java
Labels: 📬 API, 🐞 BugFix, ✨ Feature

#94 Feature/cart
  ssgserver/src/main/java/com/isekai/ssgserver/cart/service/CartService.java
Labels: 📬 API, 🐞 BugFix, ✨ Feature

#95 Feat/review
  ssgserver/src/main/java/com/isekai/ssgserver/product/entity/ReviewScore.java
  ssgserver/src/main/java/com/isekai/ssgserver/product/repository/ProductRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/product/repository/ReviewScoreRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/review/controller/ReviewController.java
  ssgserver/src/main/java/com/isekai/ssgserver/review/dto/ReviewCountDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/review/dto/ReviewCountResDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/review/dto/ReviewPhotoResDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/review/dto/ReviewProductResDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/review/dto/ReviewReqDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/review/entity/Review.java
  ssgserver/src/main/java/com/isekai/ssgserver/review/enums/ReviewType.java
  ssgserver/src/main/java/com/isekai/ssgserver/review/repository/ReviewRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/review/service/ReviewService.java
Labels: 📬 API, ✨ Feature

#97 Refector: 코드 리펙토링
  ssgserver/src/main/java/com/isekai/ssgserver/review/controller/ReviewController.java
Labels: 🔨 Refactor, 📬 API

#93 Feature/address
  ssgserver/src/main/java/com/isekai/ssgserver/deliveryAddress/controller/DeliveryAddressController.java
  ssgserver/src/main/java/com/isekai/ssgserver/deliveryAddress/entity/DeliveryAddress.java
  ssgserver/src/main/java/com/isekai/ssgserver/deliveryAddress/service/DeliveryAddressService.java
Labels: 📬 API, ✨ Feature

#99 Feat/favorite r
  ssgserver/src/main/java/com/isekai/ssgserver/member/controller/MemberFavoriteController.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/controller/MemberInfoController.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/dto/FavoriteListResDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/dto/FavoriteResDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/dto/WithdrawInfoDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/service/MemberFavoriteService.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/service/MemberInfoService.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/service/WithdrawService.java
  ssgserver/src/main/java/com/isekai/ssgserver/review/service/ReviewService.java
Labels: 🔨 Refactor, 📬 API

#101 Feat/bundle
  ssgserver/src/main/java/com/isekai/ssgserver/bundle/controller/BundleController.java
  ssgserver/src/main/java/com/isekai/ssgserver/bundle/dto/BundleCardResDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/bundle/dto/BundleInfoResDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/bundle/dto/BundleListResDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/bundle/dto/BundleProductListResDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/bundle/entity/Bundle.java
  ssgserver/src/main/java/com/isekai/ssgserver/bundle/entity/BundleProduct.java
  ssgserver/src/main/java/com/isekai/ssgserver/bundle/enums/BundleType.java
  ssgserver/src/main/java/com/isekai/ssgserver/bundle/repository/BundleProductRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/bundle/repository/BundleRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/bundle/service/BundleService.java
  ssgserver/src/main/java/com/isekai/ssgserver/product/controller/ProductController.java
Labels: 📬 API, ✨ Feature

#102 Feature/cart
  ssgserver/src/main/java/com/isekai/ssgserver/cart/controller/CartController.java
  ssgserver/src/main/java/com/isekai/ssgserver/config/CorsConfig.java
Labels: ⚙ Setting, 🐞 BugFix

#104 Feat/favorite
  ssgserver/src/main/java/com/isekai/ssgserver/member/controller/MemberFavoriteController.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/dto/FavoriteDelReqDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/dto/FavoriteDelRequestDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/repository/MemberFavoriteRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/service/MemberFavoriteService.java
Labels: 🔨 Refactor, 📬 API

#106 Feat: 일반 검색 기능
  ssgserver/src/main/java/com/isekai/ssgserver/product/controller/ProductSearchController.java
  ssgserver/src/main/java/com/isekai/ssgserver/product/repository/ProductKeywordRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/product/service/ProductSearchService.java
Labels: 📬 API, ✨ Feature

#108 Feature/category
  ssgserver/src/main/java/com/isekai/ssgserver/category/repository/CategoryProductCustomRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/product/controller/ProductController.java
Labels: 📬 API, ✨ Feature

#110 Refactor: 찜 갯수 조건 uuid 추가
  ssgserver/src/main/java/com/isekai/ssgserver/member/controller/MemberFavoriteController.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/repository/MemberFavoriteRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/service/MemberFavoriteService.java
Labels: 🔨 Refactor, 📬 API

#112 Update README.md
  README.md
Labels: 🔨 Refactor

#115 Refactor: 찜 선택 삭제 수정
  ssgserver/src/main/java/com/isekai/ssgserver/member/controller/MemberFavoriteController.java
Labels: 🔨 Refactor, 📬 API

#117 Refactor: 카테고리 찜 목록 API 수정
  ssgserver/src/main/java/com/isekai/ssgserver/category/entity/CategoryS.java
  ssgserver/src/main/java/com/isekai/ssgserver/category/repository/CategoryMRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/category/repository/CategorySRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/controller/MemberFavoriteController.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/dto/FavoriteCateResDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/service/MemberFavoriteService.java
Labels: 🔨 Refactor, 📬 API

#113 Feature/setting
  ssgserver/src/main/java/com/isekai/ssgserver/redis/RedisTestController.java
  ssgserver/src/main/java/com/isekai/ssgserver/sample/controller/SampleController.java
  ssgserver/src/main/java/com/isekai/ssgserver/sample/dto/SampleResponseDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/sample/entity/Sample.java
  ssgserver/src/main/java/com/isekai/ssgserver/sample/repository/SampleRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/sample/service/SampleService.java
Labels: ⚙ Setting, 🌏 Deploy

#119 Refactor: 카테고리 찜 목록 API 수정
  ssgserver/src/main/java/com/isekai/ssgserver/member/dto/FavoriteCateResDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/service/MemberFavoriteService.java
Labels: 🔨 Refactor, 📬 API

#121 Refactor: 찜 삭제 API 카테고리 수정
  ssgserver/src/main/java/com/isekai/ssgserver/member/repository/MemberFavoriteRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/service/MemberFavoriteService.java
Labels: 🔨 Refactor, 📬 API

#123 Feature/general-search
  ssgserver/src/main/java/com/isekai/ssgserver/product/repository/ProductKeywordRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/product/service/ProductSearchService.java
Labels: 📬 API, 🐞 BugFix, ✨ Feature

#124 Merge/develop
  README.md
  ssgserver/src/main/java/com/isekai/ssgserver/category/entity/CategoryS.java
  ssgserver/src/main/java/com/isekai/ssgserver/category/repository/CategoryMRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/category/repository/CategoryProductCustomRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/category/repository/CategorySRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/controller/MemberFavoriteController.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/dto/FavoriteCateResDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/repository/MemberFavoriteRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/member/service/MemberFavoriteService.java
  ssgserver/src/main/java/com/isekai/ssgserver/product/controller/ProductController.java
  ssgserver/src/main/java/com/isekai/ssgserver/product/repository/ProductKeywordRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/product/service/ProductSearchService.java
  ssgserver/src/main/java/com/isekai/ssgserver/redis/RedisTestController.java
  ssgserver/src/main/java/com/isekai/ssgserver/sample/controller/SampleController.java
  ssgserver/src/main/java/com/isekai/ssgserver/sample/dto/SampleResponseDto.java
  ssgserver/src/main/java/com/isekai/ssgserver/sample/entity/Sample.java
  ssgserver/src/main/java/com/isekai/ssgserver/sample/repository/SampleRepository.java
  ssgserver/src/main/java/com/isekai/ssgserver/sample/service/SampleService.java
Labels: 🌏 Deploy
